---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: 'Test GitHub Action 🧪'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: 'Test local GitHub Action'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Test against a directory containing no Python project code
      # This will not do anything, but not fail either
      - name: "Running local action: ${{ github.repository }}"
        uses: ./

      - name: "Running local action: ${{ github.repository }} [Failure Test]"
        id: failure
        uses: ./
        with:
          # Set flag to prevent the silent failure in initial test above
          exit_on_fail: true
        # Override the error condition
        continue-on-error: true

      - name: 'Error if step above did NOT fail'
        if: steps.failure.outcome == 'success'
        shell: bash
        run: |
          # Error if step above did NOT fail
          echo "Error: previous test step did NOT fail ❌"
          exit 1

      # Checkout the test Python project
      - name: "Checkout sample project repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: "lfreleng-actions/test-python-project"
          path: "test-python-project"

      # Run a valid test against it
      - name: "Run action: ${{ github.repository }}"
        uses: ./
        continue-on-error: true  # Organisation level permissions block PR
        with:
          path_prefix: "test-python-project"
          # Flag needed to prevent local/test repository checkout conflicts
          no_checkout: true
